{ config, pkgs, ... }:

{
  imports = [
    ./boot.nix
    ./network.nix
  ];

  ### General System Settings ###
  system.stateVersion = "24.11";

  ### Nix Settings ###
  nix = {
    # Automatically garbage collect to ensure disk not eaten up too quickly
    gc.automatic = true;

    # Required to enable NixOS Flakes
    settings.experimental-features = [ "nix-command" "flakes" ];
  };

  # Time zone and internationalization properties
  #
  # Update 'time.timeZone' per system as needed
  time.timeZone = "America/Los_Angeles";
  i18n.defaultLocale = "en_US.UTF-8";

  ### System Packages ###
  environment.systemPackages = with pkgs; [
    bind # dig
    curl
    ethtool
    ipcalc
    iperf3
    iw
    jq
    minicom
    mtr
    nmap
    pciutils # lspci
    tmux
    trace-cmd
    traceroute
    tree
    usbutils # lsusb
    wget

    # Vim with Nix syntax highlighting
    # TODO: Investigate moving this to using HomeManager
    ((vim_configurable.override { }).customize {
      name = "vim";
      vimrcConfig.packages.myplugins = with pkgs.vimPlugins; {
        start = [ vim-nix vim-lastplace ];
        opt = [ ];
      };
      vimrcConfig.customRC = ''
        " Generated by nix configuration
        set nocompatible
        set backspace=indent,eol,start
        " Turn on syntax highlighting by default
        syntax on
        " ...
      '';
    })
  ];

  # Set default editor to vim
  environment.variables = { EDITOR = "vim"; };

  # Enable VSCode Server service (installed as part of flake)
  services.vscode-server.enable = true;

  ### System Users ###
  # User configs in the modules/users/ folder
  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;
}
