{ config, pkgs, ... }:

{
  imports = [
    ./boot.nix
    ./network.nix
  ];

  ### General System Settings ###
  system.stateVersion = "24.11";

  # Required to enable NixOS Flakes
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Time zone and internationalization properties
  #
  # Update 'time.timeZone' per system as needed
  time.timeZone = "America/Los_Angeles";
  i18n.defaultLocale = "en_US.UTF-8";

  # Set default editor to vim
  environment.variables = { EDITOR = "vim"; };

  ### System Packages ###
  environment.systemPackages = with pkgs; [
    bind
    git
    nixpkgs-fmt
    pre-commit
    tree
    tmux
    wget

    # Vim with Nix syntax highlighting
    # TODO: Investigate moving this to using HomeManager
    ((vim_configurable.override { }).customize {
      name = "vim";
      vimrcConfig.packages.myplugins = with pkgs.vimPlugins; {
        start = [ vim-nix vim-lastplace ];
        opt = [ ];
      };
      vimrcConfig.customRC = ''
        " Generated by nix configuration
        set nocompatible
        set backspace=indent,eol,start
        " Turn on syntax highlighting by default
        syntax on
        " ...
      '';
    })
  ];
}
